// arranger.ts — auto-evolving rhythm development for the particle machine. Every
// `sectionBars` cycles a new section regenerates the 8 particle lane patterns; a 5-stage
// arc (sparse intro → dense climax → resolve) advances every `stageBars` cycles. The
// patterns are generated by COMBINING factors (climate / current / soil / weather) through
// an ENGINE (plant growth / physics oscillation / geometry quantisation). Character is kept.
import type { ParamState } from "../core/params";
import type { PulseSequencer } from "./pulse";
import { PARTICLES } from "../audio/particles";

export const ENGINES = ["PLANT", "PHYSICS", "GEOMETRY"] as const;
export const CLIMATES = ["tropical", "temperate", "arid", "polar"] as const;
export const CURRENTS = ["warm", "cold", "gyre", "upwelling"] as const;
export const SOILS = ["sand", "clay", "loam", "volcanic"] as const;
export const WEATHERS = ["clear", "rain", "storm", "fog"] as const;

const CLIMATE_V: Record<string, number> = { tropical: 0.9, temperate: 0.55, arid: 0.4, polar: 0.15 };
const CURRENT_V: Record<string, number> = { warm: 0.7, cold: 0.3, gyre: 0.5, upwelling: 0.85 };
const SOIL_V: Record<string, number> = { sand: 0.3, clay: 0.6, loam: 0.78, volcanic: 0.92 };
const WEATHER_V: Record<string, number> = { clear: 0.4, rain: 0.6, storm: 0.9, fog: 0.25 };
const STAGE_E = [0, 0.2, 0.45, 0.7, 1.0, 0.4];
const GATES = ["MANUAL", "QUANTUM", "AND", "OR"];

// base pulse density per lane [sub,thud,click,tick,pop,grain,dust,hiss]
const BASE = [0.25, 0.15, 0.45, 0.5, 0.2, 0.35, 0.25, 0.12];
// soil emphasis multiplier per lane
const SOIL_EMPH: Record<string, number[]> = {
  sand: [0.6, 0.5, 1.3, 1.3, 0.9, 0.9, 1.0, 1.2],
  clay: [1.0, 1.4, 0.9, 0.9, 0.8, 0.8, 1.3, 0.7],
  loam: [1.0, 1.0, 1.0, 1.0, 1.0, 1.1, 1.0, 1.0],
  volcanic: [1.4, 1.2, 1.0, 0.9, 1.2, 1.4, 0.9, 0.8],
};

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
}
function hash(s: string): number { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

// Euclidean rhythm: distribute k pulses across n steps as evenly as possible.
function euclid(k: number, n: number, rot: number): boolean[] {
  const out = new Array(n).fill(false);
  if (k <= 0) return out;
  k = Math.min(k, n);
  let bucket = 0;
  for (let i = 0; i < n; i++) {
    bucket += k;
    if (bucket >= n) { bucket -= n; out[(i + rot) % n] = true; }
  }
  return out;
}

export interface Factors { engine: string; climate: string; current: string; soil: string; weather: string }
export interface SectionInfo { stage: number; section: number }

export class Arranger {
  stage = 1;
  section = 0;
  private lastSec = -1;

  update(cycle: number, state: ParamState, seq: PulseSequencer, f: Factors): SectionInfo | null {
    const sectionBars = Math.max(1, Math.round(state.sectionBars as number));
    const stageBars = Math.max(1, Math.round(state.stageBars as number));
    const sec = Math.floor(cycle / sectionBars);
    if (sec === this.lastSec) return null;
    this.lastSec = sec;
    this.section = sec;
    this.stage = 1 + (Math.floor(cycle / stageBars) % 5);
    this.derive(state, seq, f, sec, this.stage);
    return { stage: this.stage, section: sec };
  }

  private derive(state: ParamState, seq: PulseSequencer, f: Factors, sec: number, stage: number): void {
    const rng = mulberry32(hash(`${f.engine}|${f.climate}|${f.current}|${f.soil}|${f.weather}|${sec}`));
    const energy = STAGE_E[stage];
    const cV = CLIMATE_V[f.climate], curV = CURRENT_V[f.current], soV = SOIL_V[f.soil], weV = WEATHER_V[f.weather];
    const emph = SOIL_EMPH[f.soil] ?? SOIL_EMPH.loam;

    // ── global feel ──
    state.bpm = clamp(Math.round(80 + cV * 44 + energy * 14 + (rng() - 0.5) * 6), 40, 200);
    state.swing = clamp(0.12 + weV * 0.34 + (f.engine === "PHYSICS" ? 0.12 * Math.sin(sec) : 0), 0, 0.7);
    state.patternDensity = clamp(0.25 + curV * 0.55, 0, 1);
    state.gateThresh = clamp(0.28 + (1 - energy) * 0.22, 0, 1);
    state.dustField = clamp(3 + weV * 22, 0, 30);
    state.warmth = clamp(0.2 + soV * 0.45, 0, 1);
    const fogDark = f.weather === "fog" ? 0.6 : f.weather === "storm" ? 1.25 : 1;
    state.lowpass = clamp(Math.round((2600 + cV * 6000) * fogDark), 400, 16000);
    state.reverbMix = clamp(0.12 + weV * 0.3, 0, 1);
    // gate mode by engine
    state.gateMode = f.engine === "GEOMETRY" ? (sec % 2 ? "AND" : "MANUAL")
      : f.engine === "PHYSICS" ? "OR"
      : GATES[2 + (sec % 2)]; // PLANT: AND / OR

    // ── regenerate the 8 lane patterns ──
    for (let l = 0; l < PARTICLES.length; l++) {
      let dens = BASE[l] * emph[l] * (0.45 + energy);
      if (f.engine === "PHYSICS") dens *= 0.5 + 0.5 * Math.sin(sec * 0.8 + l * 1.3 + curV * 6);
      dens = clamp(dens, 0, 0.95);
      let k = Math.round(dens * 16);
      let rot: number;
      if (f.engine === "GEOMETRY") { // snap pulse count to symmetric divisors
        const divs = [2, 4, 8, 16];
        k = k <= 0 ? 0 : divs.reduce((a, b) => (Math.abs(b - k) < Math.abs(a - k) ? b : a));
        rot = (l * 2) % 8;
      } else if (f.engine === "PLANT") {
        rot = Math.floor(rng() * 4) + (stage - 1); // grows/shifts as it develops
      } else {
        rot = Math.floor(rng() * 16);
      }
      seq.steps[l] = euclid(k, 16, rot);
      // probability shimmer
      const pr = seq.prob[l];
      for (let s = 0; s < 16; s++) pr[s] = 0.6 + rng() * 0.4;
    }

    // ── lane levels by soil emphasis + energy ──
    const setLvl = (name: keyof ParamState, i: number, ceil: number): void => {
      state[name] = clamp(0.25 + emph[i] * 0.3 + energy * 0.2, 0, ceil);
    };
    setLvl("subLevel", 0, 1); setLvl("thudLevel", 1, 1); setLvl("clickLevel", 2, 1);
    setLvl("tickLevel", 3, 1); setLvl("popLevel", 4, 1); setLvl("grainLevel", 5, 1);
    setLvl("dustLevel", 6, 1); setLvl("hissLevel", 7, 0.7);
  }
}
